// <auto-generated />
namespace Tienda.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InicioProyectoBrandCategoryProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicioProyectoBrandCategoryProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131820336_InicioProyectoBrand-Category-Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
